---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
# Fork data files from https://github.com/rdpeng/RepData_PeerAssessment1
# unzip("activity.zip", exdir = "data")
act <- read.csv("data/activity.csv", header = T)
act$date <- as.Date(as.character(act$date), "%Y-%m-%d")

library(dplyr)


```


## What is mean total number of steps taken per day?

```{r}
meanStepPerDay <- aggregate(act[,1], list(act$date), mean)
names(meanStepPerDay) <- c("Date","Mean.Steps")
totalStepPerDay <- aggregate(act[,1], list(act$date), sum)
names(totalStepPerDay) <- c("Date", "Total.Steps")

act_filtered <- filter(act, steps!= 0 & !is.na(steps))
medianStepPerDay <- aggregate(act_filtered[,1], list(act_filtered$date), median)
names(medianStepPerDay) <- c("Date","Median.Steps")

```


## What is the average daily activity pattern?

```{r}

totalSteps <- sum(act_filtered$steps)


# Ungrouped
act_NoNA <- filter(act, !is.na(steps))
allDayAv <- mutate(act_NoNA, avSteps=cumsum(steps), dailyCnt=cumsum(steps>=0), avg=avSteps/dailyCnt)

allDayAv$dateInterval <- paste(allDayAv$date,allDayAv$interval)






```



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
